import React, { useState } from 'react';
import { HelpCircle, ChevronDown, ShieldCheck, Cpu, Layers, Sparkles, Lock, CheckCircle2 } from 'lucide-react';

interface FaqItem {
  question: string;
  answer: string;
}

const FAQS: FaqItem[] = [
  {
    question: 'Does removing AI metadata reduce or alter image quality?',
    answer:
      'No. The tool guarantees 100% original visual quality. By utilizing lossless binary chunk surgery for PNG/JPEG or pristine 100% quality raster re-encoding, every single pixel remains identical. Only hidden metadata chunks, text comments, EXIF tables, and provenance markers are purged.',
  },
  {
    question: 'What types of AI metadata and tags are removed?',
    answer:
      'The engine automatically detects and strips: (1) C2PA / JUMBF Content Credentials manifests generated by DALL-E 3, Adobe Firefly, and Microsoft Designer; (2) Generation prompts, negative prompts, seeds, samplers, and CFG scale settings embedded by Stable Diffusion, AUTOMATIC1111, and Fooocus; (3) Full ComfyUI workflow JSON node graphs; (4) Midjourney prompt tags and software strings; (5) IPTC digitalSourceType tags such as trainedAlgorithmicMedia; and (6) Standard EXIF and software identification headers.',
  },
  {
    question: 'Why should I strip AI metadata before publishing or sharing images?',
    answer:
      'Privacy and intellectual property: Many AI generators embed your complete text prompt, private model checkpoints, seeds, and workflow configurations directly into image files. Furthermore, automated platforms, social networks, and algorithms use C2PA tags to scan, flag, or restrict algorithmic media. Stripping this metadata ensures your prompt remains private and your image file contains solely pure pixel data.',
  },
  {
    question: 'Is my image uploaded to any server or cloud database?',
    answer:
      'No. The entire process executes 100% locally inside your web browser using HTML5 Canvas and native binary typed arrays. Your image never leaves your device and is never transmitted over the network.',
  },
  {
    question: 'Which AI generators and image formats are supported?',
    answer:
      'It supports all major AI image platforms including Midjourney (v4, v5, v6), Stable Diffusion (1.5, SDXL), Flux.1, DALL-E 3 (OpenAI), ComfyUI, Adobe Firefly, NovelAI, Leonardo.ai, and Ideogram across PNG, JPEG, WebP, and AVIF image formats.',
  },
];

export const SeoKnowledgeSection: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const toggleFaq = (index: number) => {
    setOpenIndex((prev) => (prev === index ? null : index));
  };

  return (
    <section aria-labelledby="knowledge-heading" className="mt-16 sm:mt-20 border-t border-neutral-200 dark:border-neutral-800 pt-12">
      {/* Informative Article Block for Search Engines & AI Crawlers */}
      <article className="prose dark:prose-invert max-w-none mb-12">
        <div className="text-center max-w-2xl mx-auto mb-10">
          <h2 id="knowledge-heading" className="text-2xl sm:text-3xl font-extrabold text-neutral-900 dark:text-neutral-50 tracking-tight">
            How AI Metadata Removal Works
          </h2>
          <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-400">
            A privacy-first tool designed to protect your creative workflows and remove provenance tracking while preserving 100% visual fidelity.
          </p>
        </div>

        {/* 3 Pillars Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 not-prose mb-12">
          <div className="p-5 rounded-2xl bg-white dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800 shadow-2xs">
            <div className="w-10 h-10 rounded-xl bg-neutral-100 dark:bg-neutral-800 flex items-center justify-center text-neutral-900 dark:text-neutral-100 mb-3">
              <CheckCircle2 className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
            </div>
            <h3 className="font-bold text-neutral-900 dark:text-neutral-100 text-sm mb-1.5">
              100% Quality Retention
            </h3>
            <p className="text-xs text-neutral-600 dark:text-neutral-400 leading-relaxed">
              Maintains bit-level visual fidelity. PNG images stay completely lossless, and JPEGs preserve full detail without introducing compression artifacts.
            </p>
          </div>

          <div className="p-5 rounded-2xl bg-white dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800 shadow-2xs">
            <div className="w-10 h-10 rounded-xl bg-neutral-100 dark:bg-neutral-800 flex items-center justify-center text-neutral-900 dark:text-neutral-100 mb-3">
              <ShieldCheck className="w-5 h-5 text-blue-600 dark:text-blue-400" />
            </div>
            <h3 className="font-bold text-neutral-900 dark:text-neutral-100 text-sm mb-1.5">
              C2PA & Provenance Purged
            </h3>
            <p className="text-xs text-neutral-600 dark:text-neutral-400 leading-relaxed">
              Strips Content Authenticity Initiative (CAI) manifests, JUMBF markers, and IPTC algorithmic media flags used by automated scanners.
            </p>
          </div>

          <div className="p-5 rounded-2xl bg-white dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800 shadow-2xs">
            <div className="w-10 h-10 rounded-xl bg-neutral-100 dark:bg-neutral-800 flex items-center justify-center text-neutral-900 dark:text-neutral-100 mb-3">
              <Lock className="w-5 h-5 text-amber-600 dark:text-amber-400" />
            </div>
            <h3 className="font-bold text-neutral-900 dark:text-neutral-100 text-sm mb-1.5">
              Zero Server Uploads
            </h3>
            <p className="text-xs text-neutral-600 dark:text-neutral-400 leading-relaxed">
              All processing executes directly on your client device in memory. Your prompts, workflows, and images are never stored or logged.
            </p>
          </div>
        </div>
      </article>

      {/* Structured FAQ Section */}
      <section aria-labelledby="faq-heading" className="max-w-3xl mx-auto">
        <div className="text-center mb-6">
          <h2 id="faq-heading" className="text-xl sm:text-2xl font-bold text-neutral-900 dark:text-neutral-100 tracking-tight flex items-center justify-center gap-2">
            <HelpCircle className="w-5 h-5 text-neutral-500" />
            Frequently Asked Questions
          </h2>
          <p className="text-xs text-neutral-500 dark:text-neutral-400 mt-1">
            Common questions about AI image metadata, C2PA Content Credentials, and privacy.
          </p>
        </div>

        <div className="space-y-3">
          {FAQS.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div
                key={idx}
                className="bg-white dark:bg-neutral-900 rounded-xl border border-neutral-200 dark:border-neutral-800 overflow-hidden shadow-2xs transition-colors"
              >
                <button
                  type="button"
                  onClick={() => toggleFaq(idx)}
                  className="w-full text-left p-4 sm:p-5 flex items-center justify-between gap-4 font-semibold text-neutral-900 dark:text-neutral-100 text-sm hover:text-neutral-700 dark:hover:text-neutral-300 transition-colors"
                  aria-expanded={isOpen}
                >
                  <span>{faq.question}</span>
                  <ChevronDown
                    className={`w-4 h-4 text-neutral-400 shrink-0 transition-transform duration-200 ${
                      isOpen ? 'rotate-180 text-neutral-900 dark:text-neutral-100' : ''
                    }`}
                  />
                </button>

                {isOpen && (
                  <div className="px-4 pb-4 sm:px-5 sm:pb-5 text-xs sm:text-sm text-neutral-600 dark:text-neutral-400 leading-relaxed border-t border-neutral-100 dark:border-neutral-800/80 pt-3">
                    <p>{faq.answer}</p>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </section>
    </section>
  );
};
